types {
    application/wasm wasm;
}

server {
    listen 80 default_server;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location = / {
        return 302 /gallery/;
    }

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ \.wasm$ {
        default_type application/wasm;
        add_header Cache-Control "public, max-age=3600";
    }
}
